# Generated by Django 4.2.7 on 2023-12-07 02:40

from django.db import migrations

def populate_status(apps, schema_editor):
    statuses = {
        'published': 'A post that is not yet published and only visible to the author',
        'draft': 'A post that is not yet published and only visible to the author',
        'archived': 'A post that is no longer visible to the public'
    }
    Status = apps.get_model('posts', 'Status')   
    for key, value in statuses.items():
        status_obj = Status(name=key, description=value)
        status_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_status_post_status'),
    ]

    operations = [
        migrations.RunPython(populate_status),
    ]
